name: CI

on:
  push:
    branches:
      - main

jobs:
  lint_and_prettier:
    name: Lint and Prettier Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint and Format Check
        run: |
          npm run lint
          npm run prettier

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
