name: CI

on:
  push:
    branches:
      - main

jobs:
  lint_and_prettier:
    name: lint and prettier check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint and Format Check
        run: |
          npm run lint
          npm run prettier

  test:
    name: run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  deploy:
    name: deploy storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Install Dependencies
        run: npm install

      - name: Build Storybook
        run: npm run pre-deploy

      - name: Deploy Storybook
        run: npm run deploy-storybook
